### ISSUE TITLE
Well, some credit?

### ISSUE THREAD

**Issue by NaorNC** [BurntJannings/nc-headbag#1]
Don't think I deserve it?

**Comment by BurntJannings** [comment]
I am so sorry! 100% you do, I found the repository randomly, and then couldn't find it in my history or remember the username again. All credit of course goes to you as the original content maker, I am not well versed enough in UI to have done it myself!

I had a credit to original author in readme just couldn't remember name

Updating ReadMe now!

**Comment by NaorNC** [comment]
You're the man!
thanks, you have done an amazing job as well
